#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""Convenience wrapper for running clearmkvcnames directly from source tree."""


from clearmkvcnames.clearmkvcnames import main


if __name__ == '__main__':
    main()
